
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - DB_TYPE=${DB_TYPE:-postgresdb}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST:-db}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER:-postgres}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD:-postgres}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE:-slingfila}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT:-5432}
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_POSTGRESDB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE:-slingfila}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
